version: '1.0'

services:
  iam_service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SECRET_KEY=iam_service_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE=30
      - MONGODB_URL=mongodb://mongodb:27017/
      - MONGODB_DB=iam
      - MONGO_COLLECTION_USERINFO=userInfo
    
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    

volumes:
  mongodb_data:   